version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: backend-service
    ports:
      - "3000:3000" 
    networks:
      - backend-net
    depends_on:
      - database

  database:
    container_name: database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017" 
    networks:
      - backend-net 

networks:
  backend-net: