apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: nodejs-backend
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nodejs-backend 
    templates:
      metadata:
        labels:
          app: nodejs-backend
      spec:
        containers:
          - name: backend
            image: kusumaningrat16/backend-node:latest
            ports:
              - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: nodejs-backend
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110
      