version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-server
    hostname: jenkins-server
    privileged: true
    user: root
    ports:
      - "5000:5000"
      - "8080:8080"
    networks:
      - jenkins-net
      - minikube
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins-data:

networks:
  jenkins-net:
  minikube: